<?php
	use n2n\impl\web\ui\view\html\HtmlView;

	$view = HtmlView::view($view);
	$html = HtmlView::html($view);
	
	$baseColClass = 'col-md-4';
	
	$baseBoxClass = 'p-3 mb-3';
	
	$colorsPrefix =  'swatch-';
	
	$themeColors = [
			'primary' => 'Primary',
			'secondary' => 'Secondary',
			'success' => 'Success',
			'info' => 'Info',
			'warning' => 'Warning',
			'danger' => 'Danger / Error',
			'light' => 'Light',
			'dark' => 'Dark',
	];
	
	$view->useTemplate('~\view\bsTemplate.html', ['title' => 'CSS Module Test', 'cssFileName' => 'style-layout']);
?>
<p class="lead">
	This is a test of the CSS Module. Our CSS Module is inspired by <a href="http://twitter.github.com/bootstrap/" target="_blank">Twitter Bootstrap</a>.
	As the Twitter Bootstrap does not integrate to well with n2n, we decided to do our own version.
</p>

<section>
	<h2>Colors</h2>
	<p class="lead">The following colors, are generated by the CSS model:</p>
	<h3 class="mt-4">Theme Colors</h3>
	<div class="row ">
		<?php foreach($themeColors as $key => $themeColor): ?>
			<div class="<?php $html->out($baseColClass) ?>">
				<div class="<?php $html->out($baseBoxClass) ?> <?php $html->out($colorsPrefix) ?><?php $html->out($key) ?>"><?php $html->out($themeColor) ?></div>
			</div>
		<?php endforeach ?>
	</div>
	<h3 class="mt-4">Gray Colors</h3>
	<div class="row">
		<div class="<?php $html->out($baseColClass) ?>">
			<div class="<?php $html->out($baseBoxClass) ?> <?php $html->out($colorsPrefix) ?>white">white</div>
		</div>
		<?php for($grayColor = 1; $grayColor <= 9; $grayColor++): ?>
			<div class="<?php $html->out($baseColClass) ?>">
				<div class="<?php $html->out($baseBoxClass) ?> <?php $html->out($colorsPrefix) ?><?php $html->out($grayColor) ?>00">gray-<?php $html->out($grayColor) ?>00</div>
			</div>
		<?php endfor ?>
		<div class="<?php $html->out($baseColClass) ?>">
			<div class="<?php $html->out($baseBoxClass) ?> <?php $html->out($colorsPrefix) ?>black">black</div>
		</div>
	</div>
</section>

<section>
	<h2>Typography <small>Headings, paragraphs, lists and other inline type elements</small></h2>
	<p class="lead">
		Notice that with the <code>lead</code> class you can design leads. The size of the lead text depends on the prepending heading tag.
	</p>
	<hr />
	
	<div class="row">
		<div class="col-sm-6">
			<h2>Differences to Twitter Bootstrap</h2>
			<p class="lead">One of the differences to the Twitter Bootstrap is that <code>.lead</code> classed debend on the prepending heading tag.</p>
			<p>Also we try to be very consequent of deriving values from <code>baseFontSize</code> and <code>baseLineHeight</code>.</p>
			<p>There is also the possibility to <mark>hightlight</mark> texts. Use the <code>mark</code> tag to do this!</p>
		</div>
		<div class="col-sm-6">
			<h2>Emphasis, address, and abbreviation</h2>
			<p>
				There is <strong>not</strong> a big difference for <code>abbr</code>, <code>em</code>, <code>address</code> <abbr title="A Tag is an HTML command">Tags</abbr>. 
				Therefore these <abbr class="initialism" title="see before">Tags</abbr> do not get <em>a lot of attention</em> here.
			</p>
			<address>
				<strong>Hofmänner New Media</strong><br />
				Stadthausstrasse 65<br />
				8400 Winterthur
			</address>
			<small>This is <code>small</code> text...</small>
		</div>
	</div>
	<h3 class="mt-4">Headings</h3>
	<p>All HTML headings, <code class="highlighter-rouge">&lt;h1&gt;</code> through <code class="highlighter-rouge">&lt;h6&gt;</code>, are available.</p>
	<table class="table">
		<thead>
			<tr>
				<th>Heading</th>
				<th>Example</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h1&gt;&lt;/h1&gt;</code>
					</p>

				</td>
				<td><span class="h1">h1. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h2&gt;&lt;/h2&gt;</code>
					</p>

				</td>
				<td><span class="h2">h2. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h3&gt;&lt;/h3&gt;</code>
					</p>

				</td>
				<td><span class="h3">h3. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h4&gt;&lt;/h4&gt;</code>
					</p>

				</td>
				<td><span class="h4">h4. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h5&gt;&lt;/h5&gt;</code>
					</p>

				</td>
				<td><span class="h5">h5. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h6&gt;&lt;/h6&gt;</code>
					</p>

				</td>
				<td><span class="h6">h6. Bootstrap heading</span></td>
			</tr>
		</tbody>
	</table>
	<h3>Display headings</h3>
	<div class="bd-example">
		<h1 class="display-1">Display 1</h1>
		<h1 class="display-2">Display 2</h1>
		<h1 class="display-3">Display 3</h1>
		<h1 class="display-4">Display 4</h1>
	</div>
	
	<h3>Blockquotes</h3>
	<div class="bd-example">
		<blockquote class="blockquote">
			<p>The Twitter Bootstrap is a great starting point! We love the framework for all it's usefull style definitions. Nevertheless we try to make it even better!</p>
			<small>Hofmänner New Media</small>
		</blockquote>
	</div>
	
	<h3>Blockquotes - <small>Naming a source</small></h3>
	<div class="bd-example">
		<blockquote class="blockquote">
			<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing
				elit. Integer posuere erat a ante.</p>
			<footer class="blockquote-footer">
				Someone famous in <cite title="Source Title">Source Title</cite>
			</footer>
		</blockquote>
	</div>
	<h3>Blockquotes - <small>Alignment</small></h3>
	<div class="bd-example">
		<blockquote class="blockquote text-center">
			<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing
				elit. Integer posuere erat a ante.</p>
			<footer class="blockquote-footer">
				Someone famous in <cite title="Source Title">Source Title</cite>
			</footer>
		</blockquote>
	</div>
	<div class="bd-example">
		<blockquote class="blockquote text-right">
			<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing
				elit. Integer posuere erat a ante.</p>
			<footer class="blockquote-footer">
				Someone famous in <cite title="Source Title">Source Title</cite>
			</footer>
		</blockquote>
	</div>
</section>
<h2>--- old hnm - solution ---</h2>
<section>
	<h2>Boxes</h2>
	<p class="lead">This addition to Twitter Bootstrap lets you easily create boxes:</p>
	
	<div class="row">
		<div class="col-sm-4 col-sm-full-6">
			<h2>Normal Content</h2>
			<p>This is normal content</p>
		</div>
		<div class="col-sm-4 col-sm-full-6">
			<div class="box emphasized">
				<h2>Emphasized Box</h2>
				<p>You can present featured content within a <code>.box.emphasized</code>.</p>
			</div>
		</div>
		<div class="col-sm-4 col-sm-full-6">
			<div class="box inversed">
				<h2>Inversed Box</h2>
				<p>There is also the possibility of a <code>.box.inversed</code>.</p>
			</div>
		</div>
		
	</div>
	
</section>

<section>
	<h2>Links</h2>
	<div class="row">
		<div class="col-sm-4 col-sm-full-6">	
			<h3>Standard Link</h3>
			<p>This is how a <a href="">Standard Link</a> looks like.</p>
		</div>
		<div class="col-sm-4 col-sm-half-6 col-sm-half-2">
			<h3>Special Links [h3]</h3>
			<p><a href="" class="link link-external">External Link</a> <code>.link-external</code></p>
			<p><a href="" class="link link-internal">Internal Link</a> <code>.link-internal</code></p>
			<p><a href="" class="link link-email">E-Mail Link</a> <code>.link-email</code></p>
			<p><a href="" class="link link-back">Back Link</a> <code>.link-back</code></p>
		</div>
		<div class="col-sm-4 col-sm-half-6 col-sm-half-2">
			<h3>File Links [h3]</h3>
			<p><a href="" class="file">General File Link</a> <code>.file</code></p>
			<p><a href="" class="file pdf">PDF File Link</a> <code>.file.pdf</code></p>
			<p><a href="" class="file doc">DOC File Link</a> <code>.file.doc</code></p>
			<p><a href="" class="file xls">XLS File Link</a> <code>.file.xls</code></p>
			<p><a href="" class="file png">Image File Link</a> <code>.file .jpg|.gif|.png</code></p>
		</div>
	</div>
</section>
<h2>--- old hnm - solution --- END ---</h2>
<section>
	<h2>Lists</h2>
	<h3>Unstyled</h3>
	<div class="bd-example">
		<ul class="list-unstyled">
			<li>Lorem ipsum dolor sit amet</li>
			<li>Consectetur adipiscing elit</li>
			<li>Integer molestie lorem at massa</li>
			<li>Facilisis in pretium nisl aliquet</li>
			<li>Nulla volutpat aliquam velit
				<ul>
					<li>Phasellus iaculis neque</li>
					<li>Purus sodales ultricies</li>
					<li>Vestibulum laoreet porttitor sem</li>
					<li>Ac tristique libero volutpat at</li>
				</ul>
			</li>
			<li>Faucibus porta lacus fringilla vel</li>
			<li>Aenean sit amet erat nunc</li>
			<li>Eget porttitor lorem</li>
		</ul>
	</div>
	<h3>Inline</h3>
	<div class="bd-example">
		<ul class="list-inline">
			<li class="list-inline-item">Lorem ipsum</li>
			<li class="list-inline-item">Phasellus iaculis</li>
			<li class="list-inline-item">Nulla volutpat</li>
		</ul>
	</div>

	<h3>Definition-List / Description-List</h3>
	<div class="bd-example">
		<dl class="row">
			<dt class="col-sm-3">Description lists</dt>
			<dd class="col-sm-9">A description list is perfect for defining
				terms.</dd>

			<dt class="col-sm-3">Euismod</dt>
			<dd class="col-sm-9">
				<p>Vestibulum id ligula porta felis euismod semper eget lacinia odio
					sem nec elit.</p>
				<p>Donec id elit non mi porta gravida at eget metus.</p>
			</dd>

			<dt class="col-sm-3">Malesuada porta</dt>
			<dd class="col-sm-9">Etiam porta sem malesuada magna mollis euismod.</dd>

			<dt class="col-sm-3 text-truncate">Truncated term is truncated</dt>
			<dd class="col-sm-9">Fusce dapibus, tellus ac cursus commodo, tortor
				mauris condimentum nibh, ut fermentum massa justo sit amet risus.</dd>

			<dt class="col-sm-3">Nesting</dt>
			<dd class="col-sm-9">
				<dl class="row">
					<dt class="col-sm-4">Nested definition list</dt>
					<dd class="col-sm-8">Aenean posuere, tortor sed cursus feugiat,
						nunc augue blandit nunc.</dd>
				</dl>
			</dd>
		</dl>
	</div>


	<h2>--- old hnm - solution ---</h2>
	<div class="row">
		<div class="col-sm-3">
			<h3>Unordered</h3>
			<ul>
				<li>a point</li>
				<li>another one
					<ul>
						<li>some subpoint</li>
						<li>another sub</li>
					</ul>
				</li>
				<li>and this one</li>
			</ul>
		</div>
		
		<div class="col-sm-3">
			<h3>Unordered, unstyled</h3>
			<p>You can create unordered lists by using class <code>.unstyled</code>:
			<ul class="list-unstyled">
				<li>a point</li>
				<li>another one
					<ul>
						<li>some subpoint</li>
						<li>another sub</li>
					</ul>
				</li>
				<li>and this one</li>
			</ul>
		</div>
		
		<div class="col-sm-3">
			<h3>Unordered, checked</h3>
			<p>This is an <strong>addition</strong> to Twitter Bootstrap. Use class <code>.checks</code> fot the checked symbol!</p>
			<ul class="checks">
				<li>a point</li>
				<li>another one</li>
				<li>and this one</li>
			</ul>
		</div>
		
		<div class="col-sm-3">
			<h3>Ordered</h3>
			<ol>
				<li>first point</li>
				<li>this one comes in second</li>
				<li>the third one</li>
			</ol>
		</div>
	</div>
	
	<div class="row">
		<div class="col-sm-3">
			<h3>Definition List</h3>
			<dl>
				<dt>This is a title</dt>
				<dd>This is the description</dd>
				<dt>Another Title</dt>
				<dd>And an according description</dd>
			</dl>
		</div>
		<div class="col-sm-9">
			<h3>Horziontal Definition List</h3>
			<dl class="dl-horizontal">
				<dt>This is a title</dt>
				<dd>This is the description</dd>
				<dt>Another Title</dt>
				<dd>And an according description</dd>
				<dt>This is a very long title to see what happens</dt>
				<dd>
					The long title is hidden, if there is not enough space for it! see what happens, if you resize the screen! 
					Check out <code>overflow: hidden</code> and <code>text-overflow: ellipsis</code>.</dd>
			</dl>
		</div>
	</div>
	<h2>--- old hnm - solution --- END ---</h2>
</section>

<section>
	<h2>Code <small>inline and block code snipplets</small></h2>
	<p class="lead">
		Below you see some <code>pre</code> tags in action. The <code>code</code> tag is demonstrated here...
		Feel free to enhance rendering with <a href="http://code.google.com/p/google-code-prettify/">code-prettify from Google</a> or so.
	</p>
	<?php $red = '#ff0000'; ?>
	<div class="row">
		<div class="col-sm-6">
			<h3>Normal PRE</h3>
			<?php test($red) ?>
		</div>
		<div class="col-sm-6">
			<h3>PRE with Scrollbar</h3>
			<p>This <code>PRE</code> tag has the class <code>.pre-scrollable</code>:</p>
			<pre class="pre-scrollable">
			<?php var_dump($_SERVER) ?>
			</pre>
		</div>
	</div>
</section>

<section>
	<h2>Tables <small>For tabular data</small></h2>
	
	<div class="row">
		<div class="col-sm-6">
			<h3>Just a normal table</h3>
			<p>Example of a normal <code>.table</code>.</p>
			<table class="table">
				<thead>
					<tr>
						<th>Version</th>
						<th>Description</th>
						<th>Price</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="3">Try now!</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>n2n free</td>
						<td>Free for non-commercial use</td>
						<td>FREE!</td>
					</tr>
					<tr>
						<td>n2n pro</td>
						<td>Use for whatever you like! lifetime version!</td>
						<td>CHF 700.-</td>
					</tr>
				</tbody>
			</table>
		</div>
		
		<div class="col-sm-6">
			<h3>This is a striped table</h3>
			<p>Example of a <code>.table-striped</code> table.</p>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Version</th>
						<th>Description</th>
						<th>Price</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="3">Try now!</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>n2n free</td>
						<td>Free for non-commercial use</td>
						<td>FREE!</td>
					</tr>
					<tr>
						<td>n2n pro</td>
						<td>Use for whatever you like! lifetime version!</td>
						<td>CHF 700.-</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6">
			<h3>This table has borders!</h3>
			<p>Example of a table with <code>.table-bordered</code>.</p>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Version</th>
						<th>Description</th>
						<th>Price</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="3">Try now!</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>n2n free</td>
						<td>Free for non-commercial use</td>
						<td>FREE!</td>
					</tr>
					<tr>
						<td>n2n pro</td>
						<td>Use for whatever you like! lifetime version!</td>
						<td>CHF 700.-</td>
					</tr>
				</tbody>
			</table>
		</div>
		
		<div class="col-sm-6">
			<h3>A condensed table</h3>
			<p>Example of a <code>.table-condensed</code> table. Can save some space...</p>
			<table class="table table-condensed">
				<thead>
					<tr>
						<th>Version</th>
						<th>Description</th>
						<th>Price</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="3">Try now!</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td>n2n free</td>
						<td>Free for non-commercial use</td>
						<td>FREE!</td>
					</tr>
					<tr>
						<td>n2n pro</td>
						<td>Use for whatever you like! lifetime version!</td>
						<td>CHF 700.-</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
		
	<h3>Everything combined</h3>
	<p>Here we have everything combined: <code>.table. .table-bordered. .table-striped .table-condensed</code>.</p>
	<table class="table table-bordered table-striped table-condensed">
		<thead>
			<tr>
				<th>Version</th>
				<th>Description</th>
				<th>Price</th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<td colspan="3">Try now!</td>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<th>n2n free</th>
				<td>Free for non-commercial use</td>
				<td>FREE!</td>
			</tr>
			<tr>
				<th>n2n pro</th>
				<td>Use for whatever you like! lifetime version!</td>
				<td>CHF 700.-</td>
			</tr>
		</tbody>
	</table>

</section>

<section>
	<h2>Forms</h2>
	<p class="lead">There are 3 different form types (like in Twitter Bootstrap):</p>
	<div class="row">
		<div class="col-sm-4 col-sm-full-6">
			<h3>Basic Form</h3>
			<form>
				<label>Label name</label>
				<input type="text" class="form-control span3" placeholder="Type something…">
				<span class="help-block">Example block-level help text here.</span>
				<label class="checkbox">
				<input type="checkbox"> Check me out
				</label>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
		</div>
		
		<div class="col-sm-8">
			<h3>Search Form</h3>
			<form class="form-search">
				<input type="text" class="form-control search-query">
				<button type="submit" class="btn btn-default">Search</button>
			</form>

			<h3>Inline Form</h3>
			<form class="well form-inline">
				<div class="form-group">
					<label for="frm-email" class="sr-only">Email Address</label>
					<input type="text" class="form-control" id="frm-email" placeholder="Email">
				</div>
				<div class="form-group">
					<input type="password" class="form-control" placeholder="Password">
				</div>
				<label class="checkbox">
					<input type="checkbox"> Remember me
				</label>
				<button type="submit" class="btn btn-default">Sign in</button>
			</form>
		</div>
	</div>
	<h3>Horizontal Forms</h3>
	
	<form class="form-horizontal">
		<fieldset>
			<div class="form-group">
				<label class="control-label col-sm-3" for="input01">Text input</label>
				<div class="col-sm-9">
					<input class="form-control" id="input01" type="text">
					<p class="help-block">In addition to freeform text, any HTML5 text-based input appears like so.</p>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3" for="optionsCheckbox">Checkbox</label>
				<div class="col-sm-9">
					<label class="checkbox">
						<input id="optionsCheckbox" value="option1" type="checkbox">
						Option one is this and that—be sure to include why it's great
					</label>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-3 text-right">
					<label for="input02">Label</label> 
					<label for="input03">Group</label>
				</div>
				<div class="col-sm-9" class="form-group">
					<div class="row">
						<div class="col-sm-4">
							<input class="col-sm-3 form-control" id="input02" type="text">
						</div>
						<div class="col-sm-4">
							<input class="col-sm-3 form-control" id="input03" type="text">
						</div>
					</div>
					<p class="help-block">With <code>.label-group</code> you can put more input fields with labels on one line! Use also <code>.input-grid-spacer</code> to ensure correct spacing!</p>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3" for="select01">Select list</label>
				<div class="col-sm-9">
					<select id="select01" class="form-control">
						<option>something</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3" for="multiSelect">Multicon-select</label>
				<div class="col-sm-9">
					<select multiple="multiple" id="multiSelect" class="form-control">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3" for="fileInput">File input</label>
				<div class="col-sm-9">
					<input class="input-file" id="fileInput" type="file">
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3" for="textarea">Textarea</label>
				<div class="col-sm-9">
					<textarea class="form-control" id="textarea" rows="3"></textarea>
				</div>
			</div>
			<div class="col-sm-9 col-sm-offset-3">
				<input type="submit" class="btn btn-primary" value="Save changes" />
				<button class="btn btn-default">Cancel</button>
			</div>
		</fieldset>
	</form>		

	
	<div class="row">
		<div class="col-sm-6">
			<h3>Spezial Form states</h3>
			<form class="form-horizontal">
				<fieldset>
					<div class="form-group">
						<label class="control-label col-sm-4" for="focusedInput">Focused input</label>
						<div class="col-sm-8">
							<input class="input-xlarge form-control focused" id="focusedInput" value="This is focused…" type="text">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-4">Uneditable input</label>
						<div class="col-sm-8">
							<span class="input-xlarge uneditable-input">Some value here</span>
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-4" for="disabledInput">Disabled input</label>
						<div class="col-sm-8">
							<input class="input-xlarge form-control disabled" id="disabledInput" placeholder="Disabled input here…" disabled="disabled" type="text">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-4" for="optionsCheckbox2">Disabled checkbox</label>
						<div class="col-sm-8">
							<label class="">
								<input id="optionsCheckbox2" value="option1" disabled="disabled" type="checkbox">
								This is a disabled checkbox
							</label>
						</div>
					</div>
					<div class="form-group warning has-warning">
						<label class="control-label col-sm-4" for="inputWarning">Input with warning</label>
						<div class="col-sm-8">
							<input id="inputWarning" class="form-control" type="text">
							<span class="help-block">Something may have gone wrong</span>
						</div>
					</div>
					<div class="form-group error has-error">
						<label class="control-label col-sm-4" for="inputError">Input with error</label>
						<div class="col-sm-8">
							<input id="inputError" class="form-control"  type="text">
							<span class="help-block">Please correct the error</span>
						</div>
					</div>
					<div class="form-group success has-success">
						<label class="control-label col-sm-4" for="inputSuccess">Input with success</label>
						<div class="col-sm-8">
							<input id="inputSuccess" class="form-control"  type="text">
							<span class="help-block">Woohoo!</span>
						</div>
					</div>
					<div class="form-group has-success">
						<label class="control-label col-sm-4" for="selectError">Select with success</label>
						<div class="col-sm-8 ">
							<select id="selectError" class="form-control">
								<option>1</option>
								<option>2</option>
								<option>3</option>
								<option>4</option>
								<option>5</option>
							</select>
							<span class="help-block">Woohoo!</span>
						</div>
					</div>
					<div class="col-sm-8 col-sm-offset-4">
						<button type="submit" class="btn btn-primary">Save changes</button>
						<button class="btn btn-default">Cancel</button>
					</div>
				</fieldset>
			</form>
		</div>
		<div class="col-sm-6">
			<h3>More form elements</h3>
			<form class="form-horizontal">
				<fieldset>
          <div class="form-group">
            <label class="control-label col-sm-4">Alternate sizes</label>
            <div class="col-sm-8 docs-input-sizes">
              <input class="form-control" placeholder=".input-mini" type="text">
              <input class="form-control" placeholder=".input-small" type="text">
              <input class="form-control" placeholder=".input-medium" type="text">
              <p class="help-block">You may also use static classes that don't map to the grid, adapt to the responsive CSS styles, or account for varying types of col-sm-9 (e.g., <code>input</code> vs. <code>select</code>).</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="prependedInput">Prepended text</label>
            <div class="col-sm-8">
              <div class="input-group">
                <span class="input-group-addon">@</span><input class="form-control" id="prependedInput" size="16" type="text">
              </div>
              <p class="help-block">Here's some help text</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="appendedInput">Appended text</label>
            <div class="col-sm-8">
              <div class="input-group">
                <input class="form-control" id="appendedInput" size="16" type="text"><span class="input-group-addon">.00</span>
              </div>
              <span class="help-inline">Here's more help text</span>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="appendedPrependedInput">Append and prepend</label>
            <div class="col-sm-8">
              <div class="input-group">
                <span class="input-group-addon">$</span>
                <input class="form-control" id="appendedPrependedInput" size="16" type="text">
                <span class="input-group-addon">.00</span>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="appendedInputButton">Append with button</label>
            <div class="col-sm-8">
              <div class="input-group">
                <input class="form-control" id="appendedInputButton" size="16" type="text">
                <span class="input-group-btn">
                	<button class="btn btn-default" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="appendedInputButtons">Two-button append</label>
            <div class="col-sm-8">
              <div class="input-group">
                <input class="form-control" id="appendedInputButtons" size="16" type="text">
                <span class="input-group-btn btn-group">
	                <button class="btn btn-default" type="button">Search</button>
	                <button class="btn btn-default" type="button">Options</button>
                </span>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="inlineCheckboxes">Inline checkboxes</label>
            <div class="col-sm-8">
              <label class="checkbox inline">
                <input id="inlineCheckbox1" value="option1" type="checkbox"> 1
              </label>
              <label class="checkbox inline">
                <input id="inlineCheckbox2" value="option2" type="checkbox"> 2
              </label>
              <label class="checkbox inline">
                <input id="inlineCheckbox3" value="option3" type="checkbox"> 3
              </label>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4" for="optionsCheckboxList">Checkboxes</label>
            <div class="col-sm-8">
              <label class="checkbox">
                <input name="optionsCheckboxList1" value="option1" type="checkbox">
                Option one is this and that—be sure to include why it's great
              </label>
              <label class="checkbox">
                <input name="optionsCheckboxList2" value="option2" type="checkbox">
                Option two can also be checked and included in form results
              </label>
              <label class="checkbox">
                <input name="optionsCheckboxList3" value="option3" type="checkbox">
                Option three can—yes, you guessed it—also be checked and included in form results
              </label>
              <p class="help-block"><strong>Note:</strong> Labels surround all the options for much larger click areas and a more usable form.</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4">Radio buttons</label>
            <div class="col-sm-8">
              <label class="radio">
                <input name="optionsRadios" id="optionsRadios1" value="option1" checked="checked" type="radio">
                Option one is this and that—be sure to include why it's great
              </label>
              <label class="radio">
                <input name="optionsRadios" id="optionsRadios2" value="option2" type="radio">
                Option two can be something else and selecting it will deselect option one
              </label>
            </div>
          </div>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save changes</button>
            <button class="btn btn-default">Cancel</button>
          </div>
        </fieldset>
			</form>
		</div>
	</div>
	
</section>

<section>
	<h2>Buttons</h2>
	
	<div class="row">
		<div class="col-sm-4">
			<h3>One class, multiple tags</h3>
			<p>The nice thing on Twitter Bootstrap is, that buttons look the same. No mather what Tag you used:</p>
		    <a class="btn btn-default" href="">Link</a>
		    <button class="btn btn-default" type="submit">Button</button>
		    <input class="btn btn-default" type="button" value="Input" />
		    <input class="btn btn-default" type="submit" value="Submit" />
		</div>
		<div class="col-sm-4">
			<h3>Buttons for actions</h3>
			<a href="#" class="btn btn-default">Default</a><br />
			<a href="#" class="btn btn-primary">Primary</a><br />
			<a href="#" class="btn btn-info">Info</a><br />
			<a href="#" class="btn btn-success">Success</a><br />
			<a href="#" class="btn btn-warning">Warning</a><br />
			<a href="#" class="btn btn-danger">Danger</a><br />
			<a href="#" class="btn btn-inverse">Inverse</a><br />
		</div>
		<div class="col-sm-4">
			<h3>Multiple sizes</h3>
			<p>
				<button class="btn btn-default btn-lg btn-primary">Primary action</button>
				<button class="btn btn-default btn-lg">Action</button>
			</p>
			<p>
				<button class="btn btn-default btn-sm btn-primary">Primary action</button>
				<button class="btn btn-default btn-sm">Action</button>
			</p>
			<p>
				<button class="btn btn-default btn-xs btn-primary">Primary action</button>
				<button class="btn btn-default btn-xs">Action</button>
			</p>
			
			<h3>Disabled Buttons</h3>
			<a class="btn btn-large btn-primary disabled" href="#">Primary link</a>
			<a class="btn btn-large disabled" href="#">Link</a>
		</div>
	</div>
	
</section>

<section>
	<h2>Button Groups</h2>
	
	<div class="row">
		<div class="col-sm-6">
			<h3>Simple Button group</h3>
			<div class="btn-group" style="margin: 9px 0;">
				<button class="btn btn-default">Left</button>
				<button class="btn btn-default">Middle</button>
				<button class="btn btn-default">Right</button>
			</div>
		</div>
        <div class="col-sm-6">
        	<h3>More Complex Group within a toolbar</h3>
			<div class="btn-toolbar">
				<div class="btn-group">
					<button class="btn btn-default">1</button>
					<button class="btn btn-default">2</button>
					<button class="btn btn-default">3</button>
					<button class="btn btn-default">4</button>
				</div>
				<div class="btn-group">
					<button class="btn btn-default">5</button>
					<button class="btn btn-default">6</button>
					<button class="btn btn-default">7</button>
				</div>
				<div class="btn-group">
					<button class="btn btn-default">8</button>
				</div>
			</div>
        </div>
	</div>
</section>

<section>
	<h2>Nav, tabs, and pills <small>Highly customizable list-style navigation</small></h2>
	
	<div class="row">
		<div class="col-sm-6">
			<h3>Basic tabs</h3>
			<ul class="nav nav-tabs">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Profile</a></li>
				<li><a href="#">Messages</a></li>
			</ul>
		</div>
		<div class="col-sm-6">
			<h3>Basic pills</h3>
			<ul class="nav nav-pills">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Profile</a></li>
				<li><a href="#">Messages</a></li>
			</ul>
		</div>
	</div>
	<div class="row">	
		<div class="col-sm-6">
			<h3>Stacked tabs</h3>
			<ul class="nav nav-tabs nav-stacked">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Profile</a></li>
				<li><a href="#">Messages</a></li>
			</ul>
		</div>
		<div class="col-sm-6">
			<h3>Stacked pills</h3>
			<ul class="nav nav-pills nav-stacked">
				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Profile</a></li>
				<li><a href="#">Messages</a></li>
			</ul>
		</div>
	</div>
</section>

<section>
	<h2>Breadcrumbs</h2>
	<ul class="breadcrumb">
		<li class="active">Home</li>
	</ul>
	<ul class="breadcrumb">
		<li><a href="#">Home</a></li>
		<li class="active">Library</li>
	</ul>
	<ul class="breadcrumb">
		<li><a href="#">Home</a></li>
		<li><a href="#">Library</a></li>
		<li class="active">Data</li>
	</ul>
</section>

<section>
	<h2>Pagination and Pager<small></small></h2>
	<p><span class="label label-warning">Notice</span> We use <code>SPAN</code> tags in order to show inactive (disabled and active) choices.</p>

	<div class="row">
		<div class="col-sm-3">
			<nav aria-label="Page navigation">
				<ul class="pagination">
					<li class="page-item">
						<a class="page-link" href="#" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
	        				<span class="sr-only">Previous</span>
        				</a>
        			</li>
					<li class="page-item active">
						<span class="page-link">1</span>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">2</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">3</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">4</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#" aria-label="Next">
					    	<span aria-hidden="true">&raquo;</span>
					    	<span class="sr-only">Next</span>
						</a>
					</li>
				</ul>
			</nav>
		</div>
		
		<div class="col-sm-3">
			<nav aria-label="Page navigation">
				<ul class="pagination pagination-sm">
					<li class="page-item">
						<a class="page-link" href="#" aria-label="Previous">«</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">10</a>
					</li>
					<li class="page-item active">
						<span class="page-link">11</span>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">12</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="#">»</a>
					</li>
				</ul>
			</nav>
		</div>
		
		<div class="col-sm-3">
			<ul class="pagination pagination-lg">
				<li>
					<a href="#">«</a>
				</li>
				<li class="active">
					<span>10</span>
				</li>
				<li>
					<span>...</span>
				</li>
				<li>
					<a href="#">20</a>
				</li>
				<li>
					<a href="#">»</a>
				</li>
			</ul>
		</div>
		
		<div class="col-sm-3 text-center">
			<ul class="pagination">
				<li class="active">
					<span>1</span>
				</li>
				<li>
					<a href="#">2</a>
				</li>
				<li>
					<a href="#">3</a>
				</li>
				<li>
					<a href="#">4</a>
				</li>
				<li>
					<a href="#">5</a>
				</li>
			</ul>
		</div>
	</div>
</section>

<section>
	<h2>Pager <small>For quick previous and next links</small></h2>
	
	<div class="row">
		<div class="col-sm-6">
			<h3>Default</h3>
			<ul class="pager">
				<li>
					<a href="#">Previous</a>
				</li>
				<li>
					<a href="#">Next</a>
				</li>
			</ul>
		</div>
		
		<div class="col-sm-6">
			<h3>Aligned links</h3>
			<ul class="pager">
				<li class="previous">
					<a href="#">&larr; Older</a>
				</li>
				<li class="next">
					<a href="#">Newer &rarr;</a>
				</li>
			</ul>
		</div>
		
	</div>
</section>

<section>
	<h2>Inline Labels <small>Label and annotate text</small></h2>

	<div class="row">
		<div class="col-sm-6">
			<h3>Labels</h3>
			<p>
				<span class="label label-default">Default</span>
				<span class="label label-success">Success</span>
				<span class="label label-warning">Warning</span>
				<span class="label label-danger">Important</span>
				<span class="label label-info">Info</span>
			</p>
			<p>
				Label with a link: <a href="#" class="label label-danger">important!</a>
			</p>
		</div>
		
		<div class="col-sm-6">
			<h3>Badges</h3>
			<p>
				<span class="badge">1</span>
				<span class="badge badge-success">2</span>
				<span class="badge badge-warning">4</span>
				<span class="badge badge-important">6</span>
				<span class="badge badge-info">8</span>
				<span class="badge badge-inverse">10</span>
			</p>
			<p>
				Badge with a link: <a href="#" class="badge badge-important">5</a>
			</p>
		</div>
	</div>
</section>

<section>
	<h2>Alerts <small>Styles for success, warning, and error messages</small></h2>
	
	<div class="row">
		<div class="col-sm-3">
			<h3>Warning message</h3>
			<div class="alert alert-warning">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Warning!</h4>
				Best check yo self, you're not...
			</div>
		</div>
		<div class="col-sm-3">
			<h3>Error or danger message</h3>
			<div class="alert alert-danger">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Error!</h4>
				Best check yo self, you're not...
			</div>
		</div>
		<div class="col-sm-3">
			<h3>Success message</h3>
			<div class="alert alert-success">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Success!</h4>
				Best check yo self, you're not...
			</div>
		</div>
		<div class="col-sm-3">
			<h3>Info message</h3>
			<div class="alert alert-info">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Info!</h4>
				Best check yo self, you're not...
			</div>
		</div>
	</div>
</section>