<?php
	use n2n\impl\web\ui\view\html\HtmlView;
	use bstmpl\model\layout\BsModel;

	$view = HtmlView::view($view);
	$html = HtmlView::html($view);
	
	$bsModel = $view->lookup(BsModel::class);
	$view->assert($bsModel instanceof BsModel);
	
	$html->meta()->addCss('css/example-layout.css');
	
	$view->useTemplate('~\view\bsTemplate.html', ['title' => 'CSS Module Test']);
?>
<p class="lead">
	This is a test of the CSS Module. Our CSS Module is inspired by <a href="http://twitter.github.com/bootstrap/" target="_blank">Twitter Bootstrap</a>.
	As the Twitter Bootstrap does not integrate to well with n2n, we decided to do our own version.
</p>

<section>
	<h2>Colors</h2>
	<p class="lead">The following colors, are generated by the CSS model:</p>
	<h3>Colors</h3>
	<div class="row form-row">
		<?php foreach ($bsModel->getColors() as $color): ?>
			<div class="<?php $html->out(BsModel::COL_CLASS) ?>">
				<div class="<?php $html->out(BsModel::BOX_CLASS) ?> <?php $html->out(BsModel::COLOR_PREFIX) ?><?php $html->out($color) ?>"><?php $html->out($color) ?></div>
			</div>
		<?php endforeach ?>
	</div>
	<h3>Theme Colors</h3>
	<div class="row form-row">
		<?php foreach ($bsModel->getThemeColors() as $themeColor): ?>
			<div class="<?php $html->out(BsModel::COL_CLASS) ?>">
				<div class="<?php $html->out(BsModel::BOX_CLASS) ?> <?php $html->out(BsModel::COLOR_PREFIX) ?><?php $html->out($themeColor) ?>"><?php $html->out($themeColor) ?></div>
			</div>
		<?php endforeach ?>
	</div>
	<h3>Project Theme Colors</h3>
	<?php foreach ($projectThemeColors = $bsModel->getProjectThemeColors() as $key => $projectThemeColor): ?>
		<div class="row form-row">
			<?php foreach($projectThemeColors[$key] as $themeVariant): ?>
				<div class="col">
				<div class="<?php $html->out(BsModel::BOX_CLASS) ?> <?php $html->out(BsModel::COLOR_PREFIX) ?><?php $html->out($themeVariant) ?>"><?php $html->out($themeVariant) ?></div>
			</div>
			<?php endforeach ?>
		</div>
	<?php endforeach ?>
		
	<h3>Gray Colors</h3>
	<div class="row form-row">
		<?php foreach ($bsModel->getGrays() as $gray): ?>
			<div class="col">
				<div class="<?php $html->out(BsModel::BOX_CLASS) ?> <?php $html->out(BsModel::COLOR_PREFIX) ?><?php $html->out($gray) ?>"><?php $html->out($gray) ?></div>
			</div>
		<?php endforeach ?>
	</div>

	<h3>Project Gray Colors</h3>
	<div class="row form-row">
		<?php foreach ($bsModel->getProjectGrays() as $gray): ?>
			<div class="col">
				<div class="<?php $html->out(BsModel::BOX_CLASS) ?> <?php $html->out(BsModel::COLOR_PREFIX) ?><?php $html->out($gray) ?>"><?php $html->out($gray) ?></div>
			</div>
		<?php endforeach ?>
	</div>
</section>

<section>
	<h2>Typography <small>Headings, paragraphs, lists and other inline type elements</small></h2>
	<p class="lead">
		Notice that with the <code>lead</code> class you can design leads. The size of the lead text depends on the prepending heading tag.
	</p>
	<hr />
	
	<div class="row">
		<div class="col-sm-6">
			<h2>Differences to Twitter Bootstrap</h2>
			<p class="lead">One of the differences to the Twitter Bootstrap is that <code>.lead</code> classed debend on the prepending heading tag.</p>
			<p>Also we try to be very consequent of deriving values from <code>baseFontSize</code> and <code>baseLineHeight</code>.</p>
			<p>There is also the possibility to <mark>hightlight</mark> texts. Use the <code>mark</code> tag to do this!</p>
		</div>
		<div class="col-sm-6">
			<h2>Emphasis, address, and abbreviation</h2>
			<p>
				There is <strong>not</strong> a big difference for <code>abbr</code>, <code>em</code>, <code>address</code> <abbr title="A Tag is an HTML command">Tags</abbr>. 
				Therefore these <abbr class="initialism" title="see before">Tags</abbr> do not get <em>a lot of attention</em> here.
			</p>
			<address>
				<strong>Hofmänner New Media</strong><br />
				Stadthausstrasse 65<br />
				8400 Winterthur
			</address>
			<small>This is <code>small</code> text...</small>
		</div>
	</div>
	<h3>Headings</h3>
	<p>All HTML headings, <code class="highlighter-rouge">&lt;h1&gt;</code> through <code class="highlighter-rouge">&lt;h6&gt;</code>, are available.</p>
	<table class="table">
		<thead>
			<tr>
				<th>Heading</th>
				<th>Example</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h1&gt;&lt;/h1&gt;</code>
					</p>

				</td>
				<td><span class="h1">h1. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h2&gt;&lt;/h2&gt;</code>
					</p>

				</td>
				<td><span class="h2">h2. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h3&gt;&lt;/h3&gt;</code>
					</p>

				</td>
				<td><span class="h3">h3. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h4&gt;&lt;/h4&gt;</code>
					</p>

				</td>
				<td><span class="h4">h4. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h5&gt;&lt;/h5&gt;</code>
					</p>

				</td>
				<td><span class="h5">h5. Bootstrap heading</span></td>
			</tr>
			<tr>
				<td>
					<p>
						<code class="highlighter-rouge">&lt;h6&gt;&lt;/h6&gt;</code>
					</p>

				</td>
				<td><span class="h6">h6. Bootstrap heading</span></td>
			</tr>
		</tbody>
	</table>
	<h3>Display headings</h3>
	<div class="bd-example">
		<h1 class="display-1">Display 1</h1>
		<h1 class="display-2">Display 2</h1>
		<h1 class="display-3">Display 3</h1>
		<h1 class="display-4">Display 4</h1>
	</div>
	
	<h3>Blockquotes</h3>
	<div class="bd-example">
		<blockquote class="blockquote">
			<p>The Twitter Bootstrap is a great starting point! We love the framework for all it's usefull style definitions. Nevertheless we try to make it even better!</p>
			<small>Hofmänner New Media</small>
		</blockquote>
	</div>
	
	<h3>Blockquotes - <small>Naming a source</small></h3>
	<div class="bd-example">
		<blockquote class="blockquote">
			<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing
				elit. Integer posuere erat a ante.</p>
			<footer class="blockquote-footer">
				Someone famous in <cite title="Source Title">Source Title</cite>
			</footer>
		</blockquote>
	</div>
	<h3>Blockquotes - <small>Alignment</small></h3>
	<div class="bd-example">
		<blockquote class="blockquote text-center">
			<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing
				elit. Integer posuere erat a ante.</p>
			<footer class="blockquote-footer">
				Someone famous in <cite title="Source Title">Source Title</cite>
			</footer>
		</blockquote>
	</div>
	<div class="bd-example">
		<blockquote class="blockquote text-right">
			<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing
				elit. Integer posuere erat a ante.</p>
			<footer class="blockquote-footer">
				Someone famous in <cite title="Source Title">Source Title</cite>
			</footer>
		</blockquote>
	</div>
</section>
<section>
	<?php $view->import('inc\lists.html') ?>
</section>

<section>
	<h2>Code <small>inline and block code snipplets</small></h2>
	<p class="lead">
		Below you see some <code>pre</code> tags in action. The <code>code</code> tag is demonstrated here...
		Feel free to enhance rendering with <a href="http://code.google.com/p/google-code-prettify/">code-prettify from Google</a> or so.
	</p>
	<?php $red = '#ff0000'; ?>
	<div class="row">
		<div class="col-sm-6">
			<div class="box p-3">
				<h3>Normal PRE</h3>
				<?php test($red) ?>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="box p-3">
				<h3>PRE with Scrollbar</h3>
				<p>This <code>PRE</code> tag has the class <code>.pre-scrollable</code>:</p>
				<pre class="pre-scrollable">
					<?php var_dump($_SERVER) ?>
				</pre>
			</div>
		</div>
	</div>
</section>

<section>
	<?php $view->import('inc\tables.html') ?>
</section>
<section>
	<?php $view->import('inc\forms.html') ?>
</section>
<section>
	<?php $view->import('inc\buttons.html') ?>
</section>
<section>
	<?php $view->import('inc\buttons.html') ?>
</section>

<section>
	<?php $view->import('inc\navs.html') ?>
</section>

<section>
	<h2>Breadcrumbs</h2>
	<ul class="breadcrumb">
		<li class="active">Home</li>
	</ul>
	<ul class="breadcrumb">
		<li><a href="#">Home</a></li>
		<li class="active">Library</li>
	</ul>
	<ul class="breadcrumb">
		<li><a href="#">Home</a></li>
		<li><a href="#">Library</a></li>
		<li class="active">Data</li>
	</ul>
</section>

<section>
	<?php $view->import('inc\pagination.html') ?>
</section>

<section>
	<h2>Inline Labels <small>Label and annotate text</small></h2>

	<div class="row">
		<div class="col-sm-6">
			<h3>Labels</h3>
			<p>
				<span class="label label-default">Default</span>
				<span class="label label-success">Success</span>
				<span class="label label-warning">Warning</span>
				<span class="label label-danger">Important</span>
				<span class="label label-info">Info</span>
			</p>
			<p>
				Label with a link: <a href="#" class="label label-danger">important!</a>
			</p>
		</div>
		
		<div class="col-sm-6">
			<h3>Badges</h3>
			<p>
				<span class="badge">1</span>
				<span class="badge badge-success">2</span>
				<span class="badge badge-warning">4</span>
				<span class="badge badge-important">6</span>
				<span class="badge badge-info">8</span>
				<span class="badge badge-inverse">10</span>
			</p>
			<p>
				Badge with a link: <a href="#" class="badge badge-important">5</a>
			</p>
		</div>
	</div>
</section>

<section>
	<h2>Alerts <small>Styles for success, warning, and error messages</small></h2>
	
	<div class="row">
		<div class="col-sm-3">
			<h3>Warning message</h3>
			<div class="alert alert-warning">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Warning!</h4>
				Best check yo self, you're not...
			</div>
		</div>
		<div class="col-sm-3">
			<h3>Error or danger message</h3>
			<div class="alert alert-danger">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Error!</h4>
				Best check yo self, you're not...
			</div>
		</div>
		<div class="col-sm-3">
			<h3>Success message</h3>
			<div class="alert alert-success">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Success!</h4>
				Best check yo self, you're not...
			</div>
		</div>
		<div class="col-sm-3">
			<h3>Info message</h3>
			<div class="alert alert-info">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Info!</h4>
				Best check yo self, you're not...
			</div>
		</div>
	</div>
</section>